Docker Support
bartosjiri/twitch-lurker-bot pull request #10
Opened 2022-08-23 13:22 UTC by nfacha

Adds docker/docker-compose support

2022-08-28 19:26 UTC, bartosjiri requested changes
Hey @nfacha, thanks for the PR! 😍

I've added comments for some minor modifications. In general, I would prefer for users to build their image by themselves. You are still welcome to build and publish the image through your fork though!

Also, could you please update the README to let users understand how to use the script with Docker/Docker Compose? 

Thanks! 🎉

2022-08-28 19:26 UTC, bartosjiri commented on Dockerfile
> +FROM node:16
Let's use some minimal image with smaller size, e.g. `node:lts-alpine`.

2022-08-28 19:26 UTC, bartosjiri commented on docker-compose.yml
> +    image: ghcr.io/nfacha/twitch-lurker-bot:master
We'll use locally built image, replacing `image` with:
```
build:
    context: "."
```

2022-08-29 12:39 UTC, nfacha commented
> Hey @nfacha, thanks for the PR! heart_eyes
> 
> I've added comments for some minor modifications. In general, I would prefer for users to build their image by themselves. You are still welcome to build and publish the image through your fork though!
> 
> Also, could you please update the README to let users understand how to use the script with Docker/Docker Compose?
> 
> Thanks! tada

The changes have been made :)

2022-08-29 18:33 UTC, merged